/*
 * Copyright (c) 2025 ANALOGUE IT SOLUTIONS. All rights reserved.
 * Use of this source code is governed by a MIT-style license that can be
 * found in the LICENSE file.
 */

package com.aits.careesteem.view.clients.model

data class CarePlanRiskAssList(
    val data: List<Data>,
    val message: String,
    val statusCode: Int
) {
    data class Data(
        val ActivityRiskAssessment: List<ActivityRiskAssessmentData>,
        val BehaviourRiskAssessment: List<BehaviourRiskAssessmentData>,
        val COSHHRiskAssessment: List<COSHHRiskAssessmentData>,
        val EquipmentRegister: List<EquipmentRegisterData>,
        val FinancialRiskAssessment: List<FinancialRiskAssessmentData>,
        val MedicationRiskAssessment: List<MedicationRiskAssessmentData>,
        val SelfAdministrationRiskAssessment: List<SelfAdministrationRiskAssessmentData>
    ) {
        data class ActivityRiskAssessmentData(
            val action_to_be_taken: String,
            val activity: String,
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val consent: Int,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val equipment: String,
            val id: Int,
            val range: String,
            val require_support: String,
            val risk_level: String,
            val sign_1: String,
            val sign_2: String,
            val status: String,
            val task_support_required: String,
            val test_completed_on: String,
            val unique_id: Int,
            val updated_at: String
        )

        data class BehaviourRiskAssessmentData(
            val affected_by_behaviour: String,
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val consent: Int,
            val controls_adequate: String,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val frequency_potential: String,
            val id: Int,
            val identified_hazard: String,
            val level_of_risk: String,
            val other_affected_by_behaviour: String,
            val other_frequency_potential: String,
            val other_potential_hazards: String,
            val other_potential_triggers: String,
            val potential_hazards: String,
            val potential_triggers: String,
            val regulatory_measures: String,
            val risk_range: String,
            val sign_1: String,
            val sign_2: String,
            val status: String,
            val support_methods: String,
            val test_completed_on: String,
            val updated_at: String
        )

        data class COSHHRiskAssessmentData(
            val action_to_be_taken: String,
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val color: String,
            val consent: Int,
            val contact_substance: String,
            val controls: String,
            val controls_reduced: String,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val description_substance: String,
            val details_substance: String,
            val emergency_procedures: String,
            val id: Int,
            val may_it_occur: String,
            val name_of_product: String,
            val safe_alternative: String,
            val sign_1: String,
            val sign_2: String,
            val staff_aware: String,
            val status: String,
            val substance_use: String,
            val test_completed_on: String,
            val type_of_harm: String,
            val unique_id: Int,
            val updated_at: String
        )

        data class EquipmentRegisterData(
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val consent: Int,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val equipment: String,
            val equipment_description: String,
            val id: Int,
            val provided_by: String,
            val purpose: String,
            val sign_1: String,
            val sign_2: String,
            val status: String,
            val test_completed_on: String,
            val unique_id: Int,
            val updated_at: String
        )

        data class FinancialRiskAssessmentData(
            val activities_finances: String,
            val activities_finances_details: String,
            val agency_name: String,
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val consent: Int,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val family_member_name: String,
            val id: Int,
            val local_authority_name: String,
            val money_spent_by: String,
            val other: String,
            val provide_details: String,
            val requires_assistance: String,
            val responsible_party: String,
            val safe_location: String,
            val sign_1: String,
            val sign_2: String,
            val spending_details: String,
            val spending_limit: String,
            val status: String,
            val test_completed_on: String,
            val updated_at: String
        )

        data class MedicationRiskAssessmentData(
            val administering: String,
            val administering_comments: String,
            val agency_notification: String,
            val assessment_name_id: Int,
            val assisting: String,
            val assisting_comments: String,
            val client_id: Int,
            val close_date: String,
            val collecting: String,
            val collecting_comments: String,
            val consent: Int,
            val controlled_drugs: String,
            val controlled_drugs_details: String,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val id: Int,
            val medication_collection_details: String,
            val ordering: String,
            val ordering_comments: String,
            val prn_medication: String,
            val safe_storage: String,
            val sign_1: String,
            val sign_2: String,
            val specialized_support: String,
            val specialized_support_comments: String,
            val status: String,
            val storage_location: String,
            val test_completed_on: String,
            val time_specific: String,
            val time_specific_comments: String,
            val updated_at: String,
            val verbal_prompt: String,
            val verbal_prompt_comments: String
        )

        data class SelfAdministrationRiskAssessmentData(
            val agrees_to_notify: String,
            val assessment_name_id: Int,
            val client_id: Int,
            val close_date: String,
            val consent: Int,
            val created_at: String,
            val date_1: String,
            val date_2: String,
            val date_of_next_test: String,
            val difficulty_reading_label: String,
            val dosage: String,
            val dose: String,
            val id: Int,
            val medicine_name: String,
            val medicines: String,
            val missed_dose: String,
            val opens_medication: String,
            val responsible_for_reorder: String,
            val route: String,
            val safe_storage: String,
            val self_administer_fully: String,
            val self_administration: String,
            val side_effects: String,
            val sign_1: String,
            val sign_2: String,
            val special_instructions: String,
            val status: String,
            val take_medicines: String,
            val test_completed_on: String,
            val time_frequency: String,
            val time_to_take_medicines: String,
            val unique_id: Int,
            val updated_at: String
        )
    }
}