/*
 * Copyright (c) 2025 ANALOGUE IT SOLUTIONS. All rights reserved.
 * Use of this source code is governed by a MIT-style license that can be
 * found in the LICENSE file.
 */

package com.aits.careesteem.view.clients.model

data class ClientCarePlanAssessment(
    val data: List<Data>,
    val message: String,
    val statusCode: Int
) {
    data class Data(
        val ActivityAssessment: ActivityAssessmentData,
        val BehaviourAssessment: BehaviourAssessmentData,
        val BreathingAssessment: BreathingAssessmentData,
        val ClinicalAssessment: ClinicalAssessmentData,
        val CommunicationAssessment: CommunicationAssessmentData,
        val ContinenceAssessment: ContinenceAssessmentData,
        val CulturalSpiritualSocialRelationshipsAssessment: CulturalSpiritualSocialRelationshipsAssessmentData,
        val DomesticAssessment: DomesticAssessmentData,
        val EnvironmentAssessment: EnvironmentAssessmentData,
        val EquipmentAssessment: EquipmentAssessmentData,
        val FinancialAssessment: FinancialAssessmentData,
        val MedicationAssessment: MedicationAssessmentData,
        val MentalHealthAssessment: MentalHealthAssessmentData,
        val MovingHandlingAssessment: MovingHandlingAssessmentData,
        val NutritionHydrationAssessment: NutritionHydrationAssessmentData,
        val OralCareAssessment: OralCareAssessmentData,
        val PainAssessment: PainAssessmentData,
        val PersonalHygieneAssessment: PersonalHygieneAssessmentData,
        val SkinAssessment: SkinAssessmentData,
        val SleepingAssessment: SleepingAssessmentData
    ) {
        data class ActivityAssessmentData(
            val close_date: String,
            val comment_1: String,
            val comment_2: String,
            val comment_3: String,
            val comment_4: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val status_1: String,
            val status_2: String,
            val status_3: String
        )

        data class BehaviourAssessmentData(
            val close_date: String,
            val comment_5: String,
            val comment_6: String,
            val comment_7: String,
            val comment_8: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val status_5: String,
            val status_6: String,
            val status_7: String
        )

        data class BreathingAssessmentData(
            val close_date: String,
            val comment_10: String,
            val comment_11: String,
            val comment_12: String,
            val comment_13: String,
            val comment_14: String,
            val comment_9: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val status_10: String,
            val status_11: String,
            val status_12: String,
            val status_13: String,
            val status_9: String
        )

        data class ClinicalAssessmentData(
            val close_date: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String
        )

        data class CommunicationAssessmentData(
            val close_date: String,
            val comment_20: String,
            val comment_21: String,
            val comment_22: String,
            val comment_23: String,
            val comment_24: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val status_20: String,
            val status_21: String,
            val status_22: String,
            val status_23: String
        )

        data class ContinenceAssessmentData(
            val close_date: String,
            val comment_25: String,
            val comment_26: String,
            val comment_27: String,
            val comment_28: String,
            val comment_29: String,
            val comment_30: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val status_25: String,
            val status_26: String,
            val status_27: String,
            val status_28: String,
            val status_29: String
        )

        data class CulturalSpiritualSocialRelationshipsAssessmentData(
            val close_date: String,
            val comment_31: String,
            val comment_32: String,
            val comment_33: String,
            val comment_34: String,
            val comment_35: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val status_31: String,
            val status_32: String,
            val status_33: String,
            val status_34: String
        )

        data class DomesticAssessmentData(
            val close_date: String,
            val comment_36: String,
            val comment_37: String,
            val comment_38: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val status_36: String,
            val status_37: String
        )

        data class EnvironmentAssessmentData(
            val close_date: String,
            val comment_39: String,
            val comment_40: String,
            val comment_41: String,
            val comment_42: String,
            val comment_43: String,
            val comment_44: String,
            val comment_45: String,
            val comment_46: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val status_39: String,
            val status_40: String,
            val status_41: String,
            val status_42: String,
            val status_43: String,
            val status_44: String,
            val status_45: String
        )

        data class EquipmentAssessmentData(
            val close_date: String,
            val comment_47: String,
            val comment_48: String,
            val comment_49: String,
            val comment_50: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val status_47: String,
            val status_48: String,
            val status_49: String
        )

        data class FinancialAssessmentData(
            val close_date: String,
            val comment_51: String,
            val comment_52: String,
            val comment_53: String,
            val comment_54: String,
            val comment_55: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val status_51: String,
            val status_52: String,
            val status_53: String,
            val status_54: String
        )

        data class MedicationAssessmentData(
            val close_date: String,
            val comment_56: String,
            val comment_57: String,
            val comment_58: String,
            val comment_59: String,
            val comment_60: String,
            val comment_61: String,
            val comment_62: String,
            val comment_63: String,
            val comment_64: String,
            val comment_65: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_10: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val questions_name_9: String,
            val status_56: String,
            val status_57: String,
            val status_58: String,
            val status_59: String,
            val status_60: String,
            val status_61: String,
            val status_62: String,
            val status_63: String,
            val status_64: String
        )

        data class MentalHealthAssessmentData(
            val close_date: String,
            val comment_66: String,
            val comment_67: String,
            val comment_68: String,
            val comment_69: String,
            val comment_70: String,
            val comment_71: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val status_66: String,
            val status_67: String,
            val status_68: String,
            val status_69: String,
            val status_70: String
        )

        data class MovingHandlingAssessmentData(
            val close_date: String,
            val comment_72: String,
            val comment_73: String,
            val comment_74: String,
            val comment_75: String,
            val comment_76: String,
            val comment_77: String,
            val comment_78: String,
            val comment_79: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val status_72: String,
            val status_73: String,
            val status_74: String,
            val status_75: String,
            val status_76: String,
            val status_77: String,
            val status_78: String
        )

        data class NutritionHydrationAssessmentData(
            val close_date: String,
            val comment_80: String,
            val comment_81: String,
            val comment_82: String,
            val comment_83: String,
            val comment_84: String,
            val comment_85: String,
            val comment_86: String,
            val comment_87: String,
            val comment_88: String,
            val comment_89: String,
            val comment_90: String,
            val comment_91: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_10: String,
            val questions_name_11: String,
            val questions_name_12: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val questions_name_9: String,
            val status_80: String,
            val status_81: String,
            val status_82: String,
            val status_83: String,
            val status_84: String,
            val status_85: String,
            val status_86: String,
            val status_87: String,
            val status_88: String,
            val status_89: String,
            val status_90: String
        )

        data class OralCareAssessmentData(
            val close_date: String,
            val comment_100: String,
            val comment_101: String,
            val comment_102: String,
            val comment_103: String,
            val comment_104: String,
            val comment_92: String,
            val comment_93: String,
            val comment_94: String,
            val comment_95: String,
            val comment_96: String,
            val comment_97: String,
            val comment_98: String,
            val comment_99: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_10: String,
            val questions_name_11: String,
            val questions_name_12: String,
            val questions_name_13: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val questions_name_9: String,
            val status_100: String,
            val status_101: String,
            val status_102: String,
            val status_103: String,
            val status_92: String,
            val status_93: String,
            val status_94: String,
            val status_95: String,
            val status_96: String,
            val status_97: String,
            val status_98: String,
            val status_99: String
        )

        data class PainAssessmentData(
            val close_date: String,
            val comment_105: String,
            val comment_106: String,
            val comment_107: String,
            val comment_108: String,
            val comment_109: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val status_105: String,
            val status_106: String,
            val status_107: String,
            val status_108: String
        )

        data class PersonalHygieneAssessmentData(
            val close_date: String,
            val comment_110: String,
            val comment_111: String,
            val comment_112: String,
            val comment_113: String,
            val comment_114: String,
            val comment_115: String,
            val comment_116: String,
            val comment_117: String,
            val comment_118: String,
            val comment_119: String,
            val comment_120: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_10: String,
            val questions_name_11: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val questions_name_9: String,
            val status_110: String,
            val status_111: String,
            val status_112: String,
            val status_113: String,
            val status_114: String,
            val status_115: String,
            val status_116: String,
            val status_117: String,
            val status_118: String,
            val status_119: String
        )

        data class SkinAssessmentData(
            val close_date: String,
            val comment_121: String,
            val comment_122: String,
            val comment_123: String,
            val comment_124: String,
            val comment_125: String,
            val comment_126: String,
            val comment_127: String,
            val comment_128: String,
            val comment_129: String,
            val comment_130: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_10: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val questions_name_7: String,
            val questions_name_8: String,
            val questions_name_9: String,
            val status_121: String,
            val status_122: String,
            val status_123: String,
            val status_124: String,
            val status_125: String,
            val status_126: String,
            val status_127: String,
            val status_128: String,
            val status_129: String
        )

        data class SleepingAssessmentData(
            val close_date: String,
            val comment_131: String,
            val comment_132: String,
            val comment_133: String,
            val comment_134: String,
            val comment_135: String,
            val comment_136: String,
            val consent: Boolean,
            val questions_name_1: String,
            val questions_name_2: String,
            val questions_name_3: String,
            val questions_name_4: String,
            val questions_name_5: String,
            val questions_name_6: String,
            val status_131: String,
            val status_132: String,
            val status_133: String,
            val status_134: String,
            val status_135: String
        )
    }
}