package com.aits.careesteem.view.visits.db_entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.aits.careesteem.utils.AppConstant.generate24CharHexId

@Entity(tableName = "medications", primaryKeys = ["medication_id", "visitDetailsId", "createdAt"])
data class MedicationEntity(
    //@PrimaryKey val id: String = generate24CharHexId(),
    //@PrimaryKey val uniqueId: String,
    val medication_id: String,
    val visitDetailsId: String,
    val createdAt: Long,
    val nhs_medicine_name: String?,
    val medication_time: String?,
    val medication_type: String?,
    val bodyMapImageUrl: String?, // JSON string
    val bodyPartNames: String?, // JSON string
    val dose_per: Int?,
    val doses: Int?,
    val medication_route_name: String?,
    val medication_support: String?,
    val quantity_each_dose: String?,
    val prn_be_given: String?,
    val prn_offered: String?,
    val prn_user_id: String?,
    val status: String?,
    val carer_notes: String?,
    val file_name: String?,
    val prn_created_by: String?,
    val blister_pack_created_by: String?,
    val blister_pack_date: String?,
    val blister_pack_details_id: String?,
    val blister_pack_end_date: String?,
    val blister_pack_id: String?,
    val blister_pack_start_date: String?,
    val blister_pack_user_id: String?,
    val by_exact_date: String?,
    val by_exact_end_date: String?,
    val by_exact_start_date: String?,
    val client_id: String?,
    val day_name: String?,
    val scheduled_created_by: String?,
    val scheduled_date: String?,
    val scheduled_details_id: String?,
    val prn_details_id: String?,
    val scheduled_end_date: String?,
    val scheduled_id: String?,
    val scheduled_start_date: String?,
    val scheduled_user_id: String?,
    val select_preference: String?,
    val session_type: String?,
    val prn_id: String?,
    val prn_start_date: String?,
    val prn_end_date: String?,
    val time_frame: String?,
    val prn_details_status: String?,
    val additional_instructions: String?,
    val medicationSync: Boolean? = false,
    val medicationBlisterPack: Boolean? = false,
    val medicationScheduled: Boolean? = false,
    val medicationPrn: Boolean? = false,
    val medicationPrnUpdate: Boolean? = false,
)
